#!/usr/bin/env python3
"""Wave A5 — unique EEAT/content blocks. No new URLs. No fake facts."""

from __future__ import annotations

# Service slug → related industry slugs (existing only)
SERVICE_INDUSTRIES = {
    "tabela": ["perakende", "fabrika-osb", "plaza-ofis"],
    "isikli-tabela": ["perakende", "restoran-cafe", "saglik"],
    "kutu-harf": ["plaza-ofis", "perakende", "fabrika-osb"],
    "totem": ["fabrika-osb", "insaat-santiye", "plaza-ofis"],
    "arac-giydirme": ["fabrika-osb", "perakende"],
    "cam-giydirme": ["perakende", "restoran-cafe", "plaza-ofis"],
    "lightbox": ["perakende", "plaza-ofis", "saglik"],
    "display-pos": ["perakende", "insaat-santiye"],
    "ofis-branding": ["plaza-ofis", "saglik"],
    "is-guvenligi-tabelalari": ["fabrika-osb", "insaat-santiye"],
}

# Unique service body expansions (H1 unchanged; ownership unchanged)
SERVICE_A5 = {
    "tabela": {
        "intro": [
            "Tabela seçimi; mesajın kim tarafından, hangi mesafeden ve hangi ışık koşulunda okunacağına göre başlar. Aynı ölçü farklı malzemede farklı ömür ve maliyet üretir.",
            "Bu sayfada genel tabela hizmetini anlatıyoruz: ışıksız/ışığa hazır paneller, cephe kimliği ve iç bilgilendirme yüzeyleri. LED cephe sistemleri için Işıklı Tabela, ışıklı kutu için Lightbox ayrıdır.",
        ],
        "where": [
            "Mağaza ve dükkân cephelerinde ilk okunan yüzey çoğu zaman tabeladır.",
            "Plaza ve ofis girişlerinde sade, kurumsal bir panel yön ve kimlik taşır.",
            "Fabrika/depo sahasında dayanımlı dış mekân tabelaları yön ve tesis adını sabitler.",
            "İç mekânda oda, kat veya birim bilgilendirmesi için daha ince malzeme setleri tercih edilebilir.",
        ],
        "materials_extra": [
            "Kompozit panel dış dayanım ve düz yüzey isterken; forex/PVC kısa–orta ömürlü iç veya yarı dış işlerde sık kullanılır.",
            "Vinil baskı kampanya veya yenilenebilir mesajlarda; sabit kurumsal yazılarda kesim/harf veya ışıklı aileler gündeme gelir.",
            "Montaj yüzeyi (kompozit, beton, cam, sandwich panel) aparat ve delik planını belirler — keşif notu olmadan net teklif çıkmaz.",
        ],
        "process_extra": [
            "Keşifte ölçü, erişim, rüzgâr/yükseklik ve varsa site yönetimi kuralları yazılır.",
            "Tasarımda okunurluk (kontrast, harf yüksekliği, boşluk) marka dilinden önce gelir; süsleme okumayı bozuyorsa sadeleştirilir.",
            "Atölyede üretim sonrası kontrol; sahada hizalama, sabitleme ve teslim kontrolü yapılır.",
        ],
        "maintenance": [
            "Dış mekân tabelalarında periyodik temizlik ve bağlantı kontrolü ömrü uzatır.",
            "Solma, darbe veya yenileme ihtiyacı oluşursa mevcut montaj noktaları üzerinden revizyon planlanabilir.",
            "Garanti kapsamı teklifte yazılıdır; genel internet vaadi verilmez.",
        ],
        "eeat": [
            "Malt Studio tabela işlerini Tekirdağ üssünden planlar: ölçüye özel üretim, saha montajı ve sonraki servis aynı iletişim hattından yürür.",
            "Sertifika, şube sayısı veya uydurma proje metriği eklenmez. Kanıt proje sayfalarına gerçek görsellerle bağlanır.",
        ],
    },
    "isikli-tabela": {
        "intro": [
            "Işıklı tabela gece trafiği olan işletmelerde markayı ayakta tutar. Sistem; kasa, LED, güç kaynağı ve yüzeyin birlikte çalışmasıdır.",
            "Lightbox (SEG / ışıklı kutu) bu sayfanın sahibi değildir. Cephe LED tabela ihtiyacı burada; retail kutu frame için Lightbox sayfasına gidin.",
        ],
        "where": [
            "Cadde mağazaları ve eczane/klinik girişleri gece okunurluk ister.",
            "Plaza ve hizmet noktalarında yol üstü farkındalık için ışıklı kasa sık tercih edilir.",
            "24 saat açık işletmelerde ışıksız paneller çoğu zaman yetersiz kalır.",
        ],
        "materials_extra": [
            "Alüminyum kasa dayanım ve servis erişimi için seçilir; LED modül yoğunluğu cephenin parlaklığına göre ayarlanır.",
            "SMPS/güç kaynağı kalitesi arıza riskini etkiler; dış mekânda sızdırmazlık planı keşifte konuşulur.",
            "Yüzey akrilik/pleksi veya uygun difüzörlerle homojen ışık hedeflenir.",
        ],
        "process_extra": [
            "Elektrik hattı ve servis kapağı erişimi keşifte kontrol edilir.",
            "Tasarım onayı sonrası kasa üretimi ve LED yerleşimi atölyede tamamlanır.",
            "Montajda su/toz riski ve gece test ihtiyacı sahaya göre planlanır.",
        ],
        "maintenance": [
            "LED veya güç kaynağı arızasında servis için iletişime geçilir; rastgele üçüncü parti müdahale önerilmez.",
            "Dış yüzey temizliği aşındırıcı kimyasalsız yapılmalıdır.",
            "Servis kapsamı teklifte netleştirilir.",
        ],
        "eeat": [
            "Işıklı işlerde deneyim; doğru LED yoğunluğu, kasa derinliği ve montaj güvenliğinin birlikte yönetilmesinden gelir.",
            "Uydurma ‘ömür garantisi yılı’ veya sahte gece fotoğrafı eklenmez.",
        ],
    },
    "kutu-harf": {
        "intro": [
            "Kutu harf, marka adını cepheye üç boyutlu taşır. Channel letters aynı ailedir; ayrı URL açılmaz.",
            "Pleksi ve paslanmaz en sık malzeme yollarıdır. Işıklı modeller LED ile üretilir; ışıksız modeller gündüz odaklıdır.",
        ],
        "where": [
            "Plaza ve ofis cephelerinde prestij algısını hızlı yükseltir.",
            "Mağaza isim yazılarında uzak okunurluk için harf yüksekliği kritiktir.",
            "Fabrika girişlerinde dayanımlı paslanmaz veya uygun dış setler tercih edilebilir.",
            "Resepsiyon içi 3D logo ofis branding ile birlikte planlanabilir.",
        ],
        "materials_extra": [
            "Pleksi/akrilik ışıklı harflerde renk ve ışık geçirgenliği avantajı sağlar.",
            "Paslanmaz dış dayanım ve mimari dil ister; bütçe genelde daha yüksektir.",
            "Montaj yüzeyi (kompozit, taş, cam) aparat tipini belirler — keşifsiz sipariş risklidir.",
        ],
        "process_extra": [
            "Vektörel logo/font kaliteyi yükseltir; yoksa sade okunur alternatif önerilir.",
            "Harf adedi, derinlik ve ışıklı tercih üretim süresini etkiler.",
            "Sahada hizalama ve sabitleme sonrası teslim kontrolü yapılır.",
        ],
        "maintenance": [
            "Dış ortamda toz ve kuş pisliği birikimi periyodik temizlik ister.",
            "Işıklı modellerde LED servisi güç kaynağı erişimine bağlıdır.",
            "Hasarlı tek harf değişimi çoğu zaman tüm yazıyı sökmeden planlanabilir.",
        ],
        "eeat": [
            "Kutu harf üretimi ölçüye özeldir; stok harf mantığı yerine yüzeye ve markaya göre imalat yapılır.",
            "Malzeme karşılaştırması eğitim için bilgi sayfasındadır; sipariş bu hizmet URL’sindedir.",
        ],
    },
    "totem": {
        "intro": [
            "Totem; yol, otopark ve tesis yaklaşımında uzaktan algı üretir. Pylon/monument alt tipleri aynı ailede anlatılır.",
            "Taşınabilir indoor display totem Display & POS ailesindedir — bu sayfa sabit dış/tesis totemine odaklanır.",
        ],
        "where": [
            "OSB ve fabrika kapılarında tesis adı ve yön için.",
            "Plaza ve kampüs yaklaşımında marka + yön kombinasyonu.",
            "Yol kenarı görünürlükte yükseklik ve görüş açısı kritiktir.",
            "İnşaat/şantiye çevrelerinde geçici veya yarı kalıcı dikey işaretler.",
        ],
        "materials_extra": [
            "Çelik/alüminyum konstrüksiyon rüzgâr ve temel tipine göre boyutlanır.",
            "Kompozit yüzeyler baskı veya kesim grafik taşır; ışıklı kasa seçeneği gece yaklaşım için eklenir.",
            "Temel ve ankraj saha koşullarına bağlıdır; izin ihtiyacı konuma göre değişir.",
        ],
        "process_extra": [
            "Keşifte zemin, görüş mesafesi, elektrik (ışıklıysa) ve güvenlik mesafesi not edilir.",
            "Tasarım onayı sonrası gövde üretimi; saha montajı vinç/iskele planıyla yapılır.",
            "Teslimde dikeylik, bağlantı ve varsa aydınlatma kontrol edilir.",
        ],
        "maintenance": [
            "Bağlantı ve yüzey kontrolleri periyodik önerilir.",
            "Işıklı totemlerde LED/servis erişimi tasarımda bırakılmalıdır.",
            "Darbe veya grafiti sonrası panel yenileme planlanabilir.",
        ],
        "eeat": [
            "Totem işleri üretim + saha lojistiği gerektirir; Tekirdağ üssünden planlanır.",
            "Temel/statik için uydurma mühendislik iddiası yazılmaz; keşif sonrası netleşir.",
        ],
    },
    "arac-giydirme": {
        "intro": [
            "Araç giydirme; baskılı folyonun araca uygulanmasıyla hareketli marka yüzeyi oluşturur. Full wrap ve parça giydirme aynı hizmetin alt yollarıdır.",
            "Bina camı uygulamaları Cam Giydirme sayfasındadır; araç camı bu kapsamda değerlendirilir.",
        ],
        "where": [
            "Panelvan ve dağıtım araçlarında cadde görünürlüğü.",
            "Kurumsal filoda şablon standardı + araç tipi uyarlaması.",
            "Servis ve demo araçlarında saha ziyaretlerinde marka taşır.",
        ],
        "materials_extra": [
            "Cast veya kalender folyo seçimi eğrilik, süre ve bütçeye göre yapılır.",
            "Laminasyon ihtiyacı kullanıma göre konuşulur; her işte zorunlu değildir.",
            "Yüzey hazırlığı (temizlik, yağ) uygulama kalitesinin yarısıdır.",
        ],
        "process_extra": [
            "Ölçü/şablon → tasarım onayı → baskı → uygulama → kenar kontrolü.",
            "Filo işlerinde araç başına takvim çıkarılır; tek günde tüm filo iddiası verilmez.",
            "Ortam sıcaklığı uygulamayı etkiler; uygun koşul kontrol edilir.",
        ],
        "maintenance": [
            "Yıkamada yüksek basınç ve sert kimyasallar kenar kaldırmayı hızlandırabilir.",
            "Sökümde doğru folyo ile kontrollü kaldırma hedeflenir; boya durumu araca göre değişir.",
            "Hasarlı panel yenilemesi filo şablonundan yeniden basılabilir.",
        ],
        "eeat": [
            "Filo işlerinde deneyim; standart + araç uyarlamasının birlikte yönetilmesinden gelir.",
            "Uydurma ‘X yıl solmaz’ vaadi eklenmez; folyo tipi ve kullanım ömrü konuşulur.",
        ],
    },
    "cam-giydirme": {
        "intro": [
            "Cam giydirme; one way vision, transparan/baskılı folyo ve vitrin grafiklerini kapsar. Window graphics aynı ailedir.",
            "Amaç görünürlük, gizlilik ve mesaj dengesini cam yüzeyde kurmaktır.",
        ],
        "where": [
            "Mağaza vitrinlerinde kampanya ve vitrin kimliği.",
            "Showroom cephelerinde ürün/marka anlatımı.",
            "Ofis cam bölmelerinde sade gizlilik veya kurumsal desen.",
            "Giriş cephe camlarında yön ve karşılama mesajı.",
        ],
        "materials_extra": [
            "OWV dışarıdan grafik, içeriden görüş dengesi sağlar; delik oranı ışığı etkiler.",
            "Frosted/kumlama görünümü mahremiyet isterken markayı boğmadan kullanılmalıdır.",
            "Opak folyo tam kapatma içindir; vitrin ‘açıklık’ ihtiyacıyla çelişebilir.",
        ],
        "process_extra": [
            "Cam temizliği ve köşe detayı uygulama kalitesini belirler.",
            "Kampanya işlerinde hızlı yenileme için sökülebilir setler planlanabilir.",
            "Büyük yüzeylerde eklem ve gergi hatası okumayı bozar — keşif ölçüsü şarttır.",
        ],
        "maintenance": [
            "Temizlikte aşındırıcı sünger kullanılmamalıdır.",
            "Kampanya sonunda kontrollü söküm planlanır.",
            "Buğu veya kenar kalkması görülürse erken müdahale önerilir.",
        ],
        "eeat": [
            "Cam işleri üretimden çok uygulama hassasiyeti ister; saha deneyimi burada görünür.",
            "OWV eğitimi bilgi sayfasında; ticari uygulama bu URL’dedir.",
        ],
    },
    "lightbox": {
        "intro": [
            "Lightbox; arkadan veya kenardan aydınlatmalı çerçeve sistemidir. SEG / backlit fabric hızlı görsel değişimi destekler.",
            "Cephe LED tabela ihtiyacı Işıklı Tabela sayfasındadır. Bu sayfa kutu/frame lightbox ailesini taşır.",
        ],
        "where": [
            "Mağaza içi ve AVM koridorlarında premium görsel alan.",
            "Showroom ve klinik bekleme duvarlarında sakin ışıklı anlatım.",
            "Resepsiyon arkasında kurumsal görsel veya menü/iletişim panosu.",
        ],
        "materials_extra": [
            "Alüminyum kasa derinliği mekâna göre seçilir; ince kasa tercihi yaygındır.",
            "Backlit fabric ve SEG kenar sistemi görsel değişimini kolaylaştırır.",
            "Akrilik yüz alternatiflerinde çizilme ve temizlik rejimi konuşulur.",
        ],
        "process_extra": [
            "Duvar tipi, elektrik ve askı yöntemi keşifte netleşir.",
            "Kasa üretimi sonrası kumaş/görsel baskı ve gerdirme yapılır.",
            "Teslimde ışık homojenliği ve kenar gergisi kontrol edilir.",
        ],
        "maintenance": [
            "Görsel değişimi SEG’de hızlıdır; kumaş kirlenmesi için doğru temizlik önerilir.",
            "LED arızasında servis erişimi kasa tipine bağlıdır.",
            "AVM kuralları varsa uygulama penceresi ona göre planlanır.",
        ],
        "eeat": [
            "Lightbox ile ışıklı tabela ayrımı bilinçli tutulur; kullanıcıyı yanlış ürüne sürüklememek EEAT’nin parçasıdır.",
            "Yerel talep Tekirdağ üssünden keşif ile yönetilir.",
        ],
    },
    "display-pos": {
        "intro": [
            "Display & POS; mağaziçi stand, rol-up, popup ve kısa ömürlü kampanya yüzeylerini kapsar. Outdoor tesis totemi Totem sayfasındadır.",
            "Amaç satış anında veya etkinlikte hızlı kurulan, taşınabilir görünürlüktür.",
        ],
        "where": [
            "Mağaza içi ürün vurgusu ve sezon kampanyaları.",
            "Fuar / açılış / geçici satış noktaları.",
            "Şantiye veya geçici bilgilendirme panoları (kalıcı totem değil).",
        ],
        "materials_extra": [
            "Karton/forex/kompozit stand gövdeleri, baskılı vinil ve roll-up mekanikleri sık kullanılır.",
            "Adet ve süre (tek gün vs sezon) malzeme sınıfını değiştirir.",
            "Taşınabilirlik ile dayanım dengesi brief’te netleştirilir.",
        ],
        "process_extra": [
            "Brief → tasarım → baskı/üretim → teslim veya kurulum.",
            "Tekrarlayan kampanyalarda şablon standardı birim maliyeti düşürebilir.",
            "Kurulum gerekmiyorsa sevk planı ayrıca konuşulur.",
        ],
        "maintenance": [
            "Kısa ömürlü POS’ta ‘ömür garantisi’ beklenmez; yenileme modeli konuşulur.",
            "Roll-up mekaniklerinde dikkatli taşıma şarttır.",
            "Depolama koşulları baskı ömrünü etkiler.",
        ],
        "eeat": [
            "Display işleri hızlı üretim hattına yaslanır; uydurma stok adedi iddiası yok.",
            "Kalıcı cephe/totem ihtiyacı yanlışlıkla buraya düşerse Totem veya Tabela’ya yönlendirilir.",
        ],
    },
    "ofis-branding": {
        "intro": [
            "Ofis branding; workplace içinde markanın kapı, cam, duvar ve karşılama yüzeylerinde tutarlı görünmesidir. Gelecekte ayrı ‘iç mekân giydirme’ ağacı açılmaz — paket burada yönetilir.",
            "Saf cam folyo malzemesi Cam Giydirme ile paylaşılır; paket ve mekân dili bu sayfadadır.",
        ],
        "where": [
            "Plaza katı resepsiyon ve koridor kimliği.",
            "Toplantı odası / cam bölme sade markalama.",
            "Klinik veya ofis bekleme alanında sakin kurumsal dil.",
        ],
        "materials_extra": [
            "İç mekân folyoları, baskılı paneller, kutu harf/logo elemanları birlikte planlanabilir.",
            "Plaza yönetimi kuralları malzeme ve yapışkan seçimini kısıtlayabilir.",
            "Vektörel logo dosyası kaliteyi yükseltir.",
        ],
        "process_extra": [
            "Kat keşfi → alan listesi → tasarım → üretim → mesaiye göre uygulama.",
            "Kesinti riski olan alanlar mesai dışı planlanabilir.",
            "Teslimde hizalama ve yapışma kontrolü yapılır.",
        ],
        "maintenance": [
            "Cam ve folyo temizliği aşındırıcı olmadan yapılmalıdır.",
            "Yenileme veya ek oda işaretleri aynı hat üzerinden eklenir.",
            "Söküm gerektiğinde yüzey koruması konuşulur.",
        ],
        "eeat": [
            "Kurumsal yaklaşım; brief, onay ve sessiz uygulama disipliniyle görünür.",
            "Uydurma ‘X ofiste uygulandı’ metriği eklenmez; proje sayfaları kanıt kapısıdır.",
        ],
    },
    "is-guvenligi-tabelalari": {
        "intro": [
            "İş güvenliği tabelaları uyarı, zorunluluk ve acil durum işaretleridir. Oda/kat wayfinding bu ailenin sahibi değildir.",
            "Malt Studio üretim/tedarik yapar; belgelendirme kuruluşu değildir. ISO/CE iddiası uydurulmaz.",
        ],
        "where": [
            "Fabrika ve OSB üretim hatları.",
            "Depo ve lojistik sahaları.",
            "Şantiye çevreleri ve geçici saha.",
            "Ortak alan acil çıkış / toplanma yönleri.",
        ],
        "materials_extra": [
            "Kompozit/forex ve vinil standart setlerde yaygındır; dış mekânda dayanım sınıfı yükseltilir.",
            "Reflektif folyo ihtiyaç halinde değerlendirilir.",
            "Toplu setlerde listeye göre üretim yapılır — hazır ‘her yere aynı’ varsayımı yoktur.",
        ],
        "process_extra": [
            "Saha listesi / yerleşim → üretim → montaj planı → teslim.",
            "Acil çıkış ve yangın işaretlerinde konum doğruluğu kritiktir; müşteri yerleşim onayı alınır.",
            "Hızlı standart setlerde süre kısa olabilir; özel metinler onay ister.",
        ],
        "maintenance": [
            "Solma veya darbe sonrası tekil değişim planlanır.",
            "Yasal güncellemeler müşteri tarafında takip edilir; tabela üreticisi mevzuat danışmanı değildir.",
            "Toplu yenilemede mevcut delik/montaj noktaları kullanılabilir.",
        ],
        "eeat": [
            "Deneyim; saha listesini okunur, doğru konumlanmış setlere çevirmektir.",
            "Uydurma uygunluk belgesi veya denetim vaadi eklenmez.",
        ],
    },
}

INDUSTRY_A5 = {
    "fabrika-osb": {
        "problems": [
            "Tesisin yol ve kapı aksında geç bulunması.",
            "Cephe kimliği ile iç saha yönünün tutarsız olması.",
            "İSG işaretlerinin eksik, soluk veya yanlış konumda kalması.",
            "Filo araçlarının markasız veya dağınık görünmesi.",
        ],
        "workflow": [
            "Saha keşfi (kapı, cephe, iç yön, filo) → öncelik listesi → tasarım onayı → üretim → aşamalı montaj.",
            "Vinç, OSB girişi ve mesai penceresi teklife ve takvime yansır.",
        ],
        "materials": [
            "Dış dayanımlı tabela/totem gövdeleri; kutu harf için uygun dış setler.",
            "İSG için okunur, saha koşullarına uygun levha malzemeleri.",
            "Filoda araç folyo sınıfı kullanıma göre seçilir.",
        ],
        "maintenance": [
            "Dış tabela ve totem bağlantı kontrolleri periyodik yapılmalıdır.",
            "İSG setleri soluma/darbede yenilenir; mevzuat takibi müşteri tarafındadır.",
            "Filo giydirmede yıkama alışkanlığı ömrü etkiler.",
        ],
        "knowledge": ["/bilgi/totem-secim-rehberi/", "/bilgi/tabela-cesitleri/", "/bilgi/arac-giydirme-rehberi/"],
    },
    "restoran-cafe": {
        "problems": [
            "Cephede gündüz okunup gece kaybolan kimlik.",
            "Vitrinin boş veya karmaşık kampanya yüzeyi.",
            "Menü/duvar anlatımının marka diliyle uyumsuz olması.",
        ],
        "workflow": [
            "Cephe + vitrin keşfi → gece ihtiyacı kararı → tasarım → üretim → işletme saatlerine göre montaj.",
            "Kampanya folyoları sabit tabeladan ayrı yenilenebilir kalem olarak planlanabilir.",
        ],
        "materials": [
            "Gece için ışıklı tabela veya uygun aydınlatmalı yüzey.",
            "Vitrinde OWV/folyo; aşırı kapama müşteri görüşünü bozmamalıdır.",
            "İçerde lightbox veya sade paneller opsiyoneldir.",
        ],
        "maintenance": [
            "Vitrin folyo kampanya bitiminde sökülüp yenilenir.",
            "Işıklı sistemlerde LED servisi için erişim bırakılmalıdır.",
            "Yağlı mutfak çevresinde iç yüzey temizliği daha sık gerekebilir.",
        ],
        "knowledge": ["/bilgi/isikli-mi-isiksiz-mi/", "/bilgi/one-way-vision-nedir/", "/bilgi/tabela-cesitleri/"],
    },
    "saglik": {
        "problems": [
            "Aşırı reklam diliyle güven duygusunun zedelenmesi.",
            "Girişte okunmayan veya karmaşık yön.",
            "Cam ve bekleme alanında dağınık afişler.",
        ],
        "workflow": [
            "Sakin brief → giriş/ışıklı ihtiyaç → iç yön ve cam → onay → düşük kesintili uygulama.",
            "Klinik içi işaretler tıbbi içerik iddiası taşımaz; yön ve kimlik odaklıdır.",
        ],
        "materials": [
            "Sade ışıklı veya ışıksız tabela; agresif renk bombardımanından kaçınılır.",
            "Camda hafif frosted veya sade grafik.",
            "Beklemede lightbox yerine sakin duvar dili de tercih edilebilir.",
        ],
        "maintenance": [
            "Hijyen kurallarına uygun temizlik; aşındırıcı kimyasal yok.",
            "Yenilemede hasta trafiğini bozmayan pencere seçilir.",
        ],
        "knowledge": ["/bilgi/isikli-mi-isiksiz-mi/", "/bilgi/tabela-cesitleri/", "/bilgi/one-way-vision-nedir/"],
    },
    "plaza-ofis": {
        "problems": [
            "Resepsiyon ve cephede zayıf ilk izlenim.",
            "Kat içi cam/kapı işaretlerinin dağınık olması.",
            "Plaza yönetimi kurallarının son anda sürpriz yaratması.",
        ],
        "workflow": [
            "Yönetim kuralları + kat keşfi → alan listesi → tasarım → üretim → mesaiye göre uygulama.",
            "Kutu harf, cam ve ofis branding aynı pakette aşamalandırılabilir.",
        ],
        "materials": [
            "Cephede kutu harf / uygun tabela; içerde folyo ve panel setleri.",
            "Lightbox resepsiyon duvarında opsiyonel premium katmandır.",
        ],
        "maintenance": [
            "Cam folyo temizliği yumuşak yapılmalıdır.",
            "Ek oda/isimlik talepleri aynı hat üzerinden eklenir.",
        ],
        "knowledge": ["/bilgi/kutu-harf-malzemeler/", "/bilgi/tabela-cesitleri/", "/bilgi/one-way-vision-nedir/"],
    },
    "insaat-santiye": {
        "problems": [
            "Proje mesajının şantiye çevresinde görünmemesi.",
            "Geçici yön ve uyarı eksikliği.",
            "Kalıcı çözümle geçici ihtiyacın karıştırılması.",
        ],
        "workflow": [
            "Saha turu → geçici/kalıcı ayrımı → hızlı üretim → güvenli montaj → proje bitiminde söküm planı.",
            "Display/POS tipi yüzeyler kısa süreli kampanya için; totem/tabela daha kalıcı ihtiyaçlar içindir.",
        ],
        "materials": [
            "Hızlı üretim panoları, dayanımlı dış levhalar, İSG uyarı setleri.",
            "Geçici işlerde aşırı pahalı malzeme çoğu zaman gereksizdir.",
        ],
        "maintenance": [
            "Şantiye koşullarında darbe/solma sık görülür; yenileme bütçesi baştan konuşulur.",
            "İş bitiminde söküm ve yüzey bırakma durumu netleştirilir.",
        ],
        "knowledge": ["/bilgi/tabela-cesitleri/", "/bilgi/totem-secim-rehberi/", "/bilgi/tabela-fiyati/"],
    },
    "perakende": {
        "problems": [
            "Cadde kotunda okunmayan mağaza adı.",
            "Vitrinin güncellenememesi.",
            "Açılışta eksik ışıklı + vitrin paketi.",
        ],
        "workflow": [
            "Cephe/vitrin keşfi → gece ihtiyacı → tasarım → üretim → açılış öncesi montaj penceresi.",
            "Kampanya folyoları sabit tabeladan ayrı yenileme döngüsüne alınabilir.",
        ],
        "materials": [
            "Işıklı tabela + OWV/vitrin folyo sık pakettir.",
            "İçerde display/POS ve lightbox sezonluk destek olabilir.",
        ],
        "maintenance": [
            "Vitrin kampanya bitiminde yenilenir.",
            "Işıklı sistem servis erişimi korunmalıdır.",
        ],
        "knowledge": ["/bilgi/isikli-mi-isiksiz-mi/", "/bilgi/one-way-vision-nedir/", "/bilgi/tabela-fiyati/"],
    },
}

# Educational expansions per article (keep H1 = title from ARTICLES)
ARTICLE_A5 = {
    "tabela-cesitleri": {
        "advantages": ["Doğru tip okunurluk ve bütçeyi dengeler.", "Keşif sonrası seçim hata riskini düşürür."],
        "disadvantages": ["Yanlış tip (ör. gece ihtiyacında ışıksız) görünürlüğü bozar.", "Aşırı süsleme okumayı zorlaştırır."],
        "mistakes": ["Sadece fiyata bakmak", "Lightbox ile ışıklı tabelayı karıştırmak", "Keşifsiz ölçü vermek", "İç/dış malzeme ayırmamak"],
        "buying": ["Önce kim/nereden okuyacak sorusunu yazın.", "Gece ihtiyacını evet/hayır netleştirin.", "Montaj yüzeyi fotoğrafı paylaşın.", "Siparişi ilgili hizmet sayfasından ilerletin."],
        "maintenance": ["Dış yüzeyleri aşındırıcı olmadan temizleyin.", "Bağlantı gevşekliği erken müdahale ister.", "Kampanya yüzeylerini sabit tabeladan ayrı yenileyin."],
        "faqs": [
            ("Bu yazıdan sipariş verilir mi?", "Hayır; eğitimdir. Tabela siparişi /hizmetler/tabela/ altındadır."),
            ("En doğru tabela hangisi?", "Konum, gece ihtiyacı ve bütçeye göre değişir; tek cevap yoktur."),
            ("Tekirdağ’da kim uygular?", "Keşif için /bolgeler/tekirdag/ veya WhatsApp."),
        ],
    },
    "isikli-mi-isiksiz-mi": {
        "advantages": ["Işıklı: gece görünürlük.", "Işıksız: daha sade maliyet ve bakım."],
        "disadvantages": ["Işıklı: elektrik + servis katmanı.", "Işıksız: gece kaybolma riski."],
        "mistakes": ["Gece trafiğini yok saymak", "Lightbox’ı cephe tabela sanmak", "LED yoğunluğunu abartmak", "Servis erişimini tasarlamamak"],
        "buying": ["İşletme saatlerini yazın.", "Cephe derinliği ve elektrik durumunu paylaşın.", "Karar sonrası /hizmetler/isikli-tabela/ veya /hizmetler/tabela/ seçin."],
        "maintenance": ["Işıklıda LED/güç kaynağı servisi planlı olmalıdır.", "Işıksızda solma ve darbe kontrolü yeterlidir."],
        "faqs": [
            ("Lightbox aynı şey mi?", "Hayır. Lightbox ayrı sayfadadır."),
            ("Neon şart mı?", "Hayır; LED ışıklı tabela yaygındır."),
            ("Sipariş nereden?", "/hizmetler/isikli-tabela/ veya ışıksız için /hizmetler/tabela/."),
        ],
    },
    "kutu-harf-malzemeler": {
        "advantages": ["Pleksi: ışık ve renk esnekliği.", "Paslanmaz: dış dayanım ve prestij algısı."],
        "disadvantages": ["Pleksi: çizilme/temizlik hassasiyeti olabilir.", "Paslanmaz: daha yüksek bütçe."],
        "mistakes": ["Fontu raster görselden büyütmek", "Montaj yüzeyini varsaymak", "Işıklı/ışıksız kararı ertelemek"],
        "buying": ["Vektörel logo gönderin.", "Cephe malzemesini fotoğraflayın.", "Sipariş /hizmetler/kutu-harf/."],
        "maintenance": ["Dış temizlik yumuşak yapılmalı.", "Işıklı harflerde servis kapağı erişimi korunmalı."],
        "faqs": [
            ("Channel letters nedir?", "Kutu harfin yaygın adıdır; ayrı URL yok."),
            ("Hangisi daha iyi?", "Mimari ve bütçeye göre; tek kazanan yok."),
            ("Sipariş?", "/hizmetler/kutu-harf/."),
        ],
    },
    "one-way-vision-nedir": {
        "advantages": ["Dışarıdan mesaj, içeriden görüş dengesi.", "Kampanya yenilemesine uygun."],
        "disadvantages": ["Delik oranı içeriyi karartabilir.", "Yanlış uygulama kenar/hava hatası yapar."],
        "mistakes": ["Kirli cama uygulama", "Aşırı kapalı vitrin", "Araç camı ile bina camını aynı sanmak"],
        "buying": ["Cam ölçüleri ve iç aydınlatmayı paylaşın.", "Uygulama /hizmetler/cam-giydirme/."],
        "maintenance": ["Aşındırıcı sünger kullanmayın.", "Kampanya bitiminde kontrollü söküm."],
        "faqs": [
            ("İçerisi tamamen görünür mü?", "Delik oranına ve ışığa bağlıdır."),
            ("Araçta kullanılır mı?", "Araç camı araç giydirme kapsamında değerlendirilir."),
            ("Sipariş?", "/hizmetler/cam-giydirme/."),
        ],
    },
    "arac-giydirme-rehberi": {
        "advantages": ["Mobil görünürlük.", "Filoda tutarlı şablon."],
        "disadvantages": ["Yüzey hazırlığı kötüyse ömür kısalır.", "Yanlış yıkama kenar kaldırır."],
        "mistakes": ["Full wrap’i her araca zorlamak", "Boyayı peşin mahvetmek varsayımı", "Filoyu tek günde bitirme vaadi beklemek"],
        "buying": ["Araç listesi ve fotoğraflar.", "Full/parça tercihi.", "Sipariş /hizmetler/arac-giydirme/."],
        "maintenance": ["Yüksek basıncı kenarlardan uzak tutun.", "Hasarda panel yenilemesi şablondan yapılır."],
        "faqs": [
            ("Boya zarar görür mü?", "Doğru folyo/uygulamada kontrollü söküm hedeflenir; araç durumuna göre değişir."),
            ("Kışın olur mu?", "Ortam sıcaklığı uygunsa."),
            ("Sipariş?", "/hizmetler/arac-giydirme/."),
        ],
    },
    "tabela-fiyati": {
        "advantages": ["Faktörleri bilmek teklifi okunaklı kılar.", "Keşif sonrası netlik sürprizi azaltır."],
        "disadvantages": ["İnternet ‘m² fiyatı’ yanıltıcıdır.", "Keşifsiz rakam bağlayıcı değildir."],
        "mistakes": ["En ucuz teklifi tek kriter yapmak", "Montajı yok saymak", "Geo fiyatı hizmet sayfasından beklemek"],
        "buying": ["Ölçü + fotoğraf + gece ihtiyacı gönderin.", "Net teklif WhatsApp/telefon ile istenir.", ],
        "maintenance": ["Ucuz malzeme kısa ömürle pahalıya gelebilir.", "Servis kapsamını teklifte sorun."],
        "faqs": [
            ("Sabit liste var mı?", "Hayır."),
            ("Bu sayfa teklif midir?", "Hayır; eğitimdir."),
            ("Teklif nasıl?", "Keşif sonrası yazılı iletişim."),
        ],
    },
    "totem-secim-rehberi": {
        "advantages": ["Uzaktan algı.", "Tesis/yol yaklaşımında yön + kimlik."],
        "disadvantages": ["Temel/izin maliyeti eklenebilir.", "Yanlış yükseklik okumayı bozar."],
        "mistakes": ["Indoor display’i outdoor totem sanmak", "Görüş mesafesini yok saymak", "Temeli sonraya bırakmak"],
        "buying": ["Konum fotoğrafı ve yaklaşım yönü.", "Işıklı ihtiyaç.", "Sipariş /hizmetler/totem/."],
        "maintenance": ["Bağlantı ve yüzey kontrolü.", "Işıklıysa LED servis erişimi."],
        "faqs": [
            ("Pylon ayrı mı?", "Aynı aile; ayrı doorway yok."),
            ("Display totem?", "/hizmetler/display-pos/."),
            ("Sipariş?", "/hizmetler/totem/."),
        ],
    },
}


# Wave A5 depth expansions — unique per slug, no shared filler paragraphs
SERVICE_EXPAND = {
    "tabela": [
        "Tabela işinde en sık hata, ölçü almadan katalog fiyatı istemektir. Cephe eğimi, bağlantı yüzeyi ve görüş mesafesi rakamı değiştirir.",
        "Işıksız tabela gece ihtiyacı yoksa doğru tercihtir; gece trafiği varsa Işıklı Tabela sayfasına geçmek gerekir. Bu ayrım ownership’i de korur.",
        "İç yön tabelası ile cephe tabelası aynı malzeme ailesinden gelse bile okunurluk ve dayanım kriterleri farklıdır.",
        "Yenileme işlerinde eski söküm, delik izleri ve boya rötuşu teklife ayrıca yansıyabilir; peşin ‘dahil’ varsayılmamalıdır.",
        "Kurumsal zincirlerde şablon standardı birim maliyeti düşürebilir; tek şube işinde ise ölçüye özel üretim öne çıkar.",
        "Kalite kontrolde hizalama, kenar bitiş ve montaj güvenliği teslim öncesi kontrol edilir; eksik varsa sahada konuşulur.",
        "Tekirdağ dışı koridor işlerinde lojistik süresi keşif notuna yazılır; ayrı city URL’si olmayan ilçeler operasyonel kapsamda kalır.",
    ],
    "isikli-tabela": [
        "Işıklı tabela kararında ilk filtre işletme saatleridir. Gece kapalı bir noktada LED yatırımı çoğu zaman gereksizdir.",
        "Kasa derinliği LED tipini ve servis erişimini etkiler; ince görünüm isteği ile servis kolaylığı dengelenmelidir.",
        "Su ve toz riski dış cephede yüksektir; conta ve drenaj detayı keşifte konuşulmadan üretim başlamamalıdır.",
        "Aşırı parlak LED hem komşuyu rahatsız eder hem okunurluğu bozar; yoğunluk cepheye göre ayarlanır.",
        "Lightbox ihtiyacı retail/AVM içi kutu ise bu sayfa değil Lightbox URL’si doğrudur — yanlış ürün EEAT’yi zedeler.",
        "Gece testi mümkünse montaj sonrası yapılır; mümkün değilse güç ve bağlantı kontrolü teslim kriteridir.",
        "Servis çağrılarında önce güç kaynağı ve bağlantı kontrol edilir; rastgele LED değişimi önerilmez.",
    ],
    "kutu-harf": [
        "Harf yüksekliği okuma mesafesine göre seçilir; gösteriş için büyütmek her zaman doğru değildir.",
        "Paslanmaz seçildiğinde kaynak/montaj izinin mimariye uyumu konuşulmalıdır.",
        "Işıklı kutu harfte yan aydınlatma ile ön yüz difüzörü farklı görünüm üretir; brief’te netleştirilir.",
        "Cam cepheye montajda delik ve aparat planı kritiktir; keşifsiz sipariş risklidir.",
        "Font lisansları müşteri sorumluluğundadır; biz üretim dosyasını teknik kalite için isteriz.",
        "Tek harf hasarında tüm yazıyı sökmek çoğu zaman gerekmez; parça üretim planlanabilir.",
        "Ofis içi 3D logo ile dış cephe harfi farklı malzeme sınıfına girebilir; paket ofis branding ile ayrılabilir.",
    ],
    "totem": [
        "Totem yüksekliği araç hızı ve görüş açısına göre belirlenir; ‘ne kadar yüksekse o kadar iyi’ yaklaşımı yanlıştır.",
        "Temel tipi zemin koşullarına bağlıdır; uydurma statik hesap yayınlanmaz, keşif sonrası netleşir.",
        "Işıklı totemlerde kaçak ve servis erişimi tasarımda bırakılmazsa bakım maliyeti artar.",
        "Pylon adı aynı ailede kalır; ayrı doorway URL açılmaz.",
        "Indoor display totem ile outdoor tesis totemi karıştırılmamalıdır — Display & POS ayrıdır.",
        "OSB girişlerinde güvenlik ve araç trafiği montaj penceresini belirler.",
        "Grafik paneli değişebilir tasarlanırsa ileride yenileme maliyeti düşer.",
    ],
    "arac-giydirme": [
        "Parça giydirme çoğu filoda yeterli görünürlük sağlar; full wrap her zaman zorunlu değildir.",
        "Eğri yüzeylerde cast folyo tercih nedeni uygulama kalitesidir; her işte şart değildir ama konuşulur.",
        "Araç boyasının durumu söküm sonucunu etkiler; peşin ‘boya bozulmaz’ garantisi verilmez.",
        "Filo şablonunda kapı tutacakları ve cam sınırları standartlaştırılır.",
        "Uygulama sonrası kenar kontrolü yapılmadan araç teslim edilmez.",
        "Kış uygulamasında ortam sıcaklığı uygun değilse iş ertelenir; kalitesiz yapışma riski alınmaz.",
        "Bina camı ihtiyacı bu sayfada değil Cam Giydirme’dedir.",
    ],
    "cam-giydirme": [
        "Vitrinde mesaj hiyerarşisi bozulursa ürün değil kalabalık görünür; sade brief daha iyidir.",
        "OWV delik oranı iç aydınlatmaya göre seçilir; karanlık mağazada görüş zayıflayabilir.",
        "Frosted görünüm mahremiyet isterken marka logosunu boğmamalıdır.",
        "Köşe ve fitil detayı uygulama kalitesinin göstergesidir.",
        "Kampanya folyosu sabit tabela gibi düşünülmemelidir; yenileme döngüsü baştan planlanır.",
        "Plaza camında yönetim kuralları yapışkan tipini kısıtlayabilir.",
        "Araç camı filo işlerinde araç giydirme kapsamında ele alınır.",
    ],
    "lightbox": [
        "Lightbox’ta kumaş gergisi bozulursa ışık lekesi oluşur; SEG kenar kalitesi kritiktir.",
        "AVM kuralları kasa tipi ve montaj saatini belirleyebilir.",
        "Görsel değişim sıklığı yüksekse SEG avantajı öne çıkar.",
        "Cephe LED tabela ihtiyacı buraya düşmemelidir; Işıklı Tabela owner’ıdır.",
        "Resepsiyon duvarında lightbox + ofis branding birlikte planlanabilir.",
        "İnce kasa isteği elektrik ve soğutma ihtiyacıyla dengelenir.",
        "Serviste kumaş değişimi ile LED değişimi ayrı kalemlerdir.",
    ],
    "display-pos": [
        "POS ömrü kısa olabilir; malzeme sınıfı kullanım süresine göre seçilir.",
        "Fuar standında taşıma ve kurulum süresi brief’in parçasıdır.",
        "Outdoor kalıcı totem ihtiyacı Display sayfasında çözülmez.",
        "Tekrarlayan kampanyalarda baskı şablonu saklanır.",
        "Roll-up mekaniği ucuz ama hassastır; taşıma eğitimi gerekir.",
        "Adet arttıkça birim maliyet düşebilir; peşin oran vaadi yoktur.",
        "Şantiye panoları geçici ise söküm planı baştan konuşulur.",
    ],
    "ofis-branding": [
        "Ofis işinde ilk izlenim resepsiyonda kurulur; koridor işaretleri ikinci katmandır.",
        "Plaza yönetimi onayı gecikirse takvim kayar; keşifte sorulur.",
        "Cam folyo ile kutu harf aynı günde uygulanabilir ama alan sırası planlanır.",
        "Aşırı logo tekrarı kurumsal algıyı zayıflatır; sade dil tercih edilir.",
        "Mesai içi uygulama gürültü/kesinti yaratabilir; alternatif pencere sunulur.",
        "Kapı isimlikleri pakete eklenebilir; standart set varsayılmaz.",
        "İç mekân için ayrı ‘giydirme’ URL’si açılmaz — paket burada kalır.",
    ],
    "is-guvenligi-tabelalari": [
        "İSG tabelası tıbbi veya yasal danışmanlık yerine geçmez; doğru konum müşteri onayıyla işlenir.",
        "Acil çıkış işaretinde yükseklik ve görüş hattı kritiktir.",
        "Wayfinding (oda numarası) bu ailenin H1’i değildir.",
        "Toplu setlerde Excel/liste ile üretim hatası azalır.",
        "Dış mekân İSG’de UV ve darbe dayanımı yükseltilir.",
        "Reflektif ihtiyaç gece saha hareketine göre konuşulur.",
        "Belgelendirme kuruluşu değiliz; uydurma uygunluk belgesi eklenmez.",
    ],
}

INDUSTRY_EXPAND = {
    "fabrika-osb": [
        "OSB sahasında tabela çoğu zaman tek ürün değil pakettir: kapı totemi, cephe yazısı ve İSG seti birlikte okunur.",
        "Ağır araç trafiği montaj güvenliğini etkiler; vinç ve yol kapama ihtiyacı keşifte yazılır.",
        "Filo giydirme tesis tabelasıyla aynı marka dilini paylaşmazsa saha algısı bölünür.",
        "Tozlu ortamda malzeme sınıfı ve temizlik periyodu baştan konuşulmalıdır.",
        "İSG yenilemesi üretim hattı duruşuna göre planlanır; uydurma ‘aynı gün biter’ vaadi yok.",
    ],
    "restoran-cafe": [
        "Cafe’de vitrin boşluğu kadar mutfak kokusu/yağ buharı iç yüzey seçimini etkiler.",
        "Gece açık işletmede ışıksız cephe çoğu zaman yetersiz kalır.",
        "Sezon menüleri için yenilenebilir cam yüzeyi sabit tabeladan ayrılmalıdır.",
        "Aşırı kalabalık vitrin grafiği ürün yerine gürültü üretir.",
        "Montaj penceresi servis saatlerine göre sabah erken veya kapalı güne alınabilir.",
    ],
    "saglik": [
        "Sağlık noktasında agresif kampanya dili güveni zedeler; sakin hiyerarşi tercih edilir.",
        "Bekleme alanı tabelası tıbbi iddia taşımaz; yön ve kimlik odaklıdır.",
        "Hijyen kuralları malzeme ve temizlik rejimini etkiler.",
        "Işıklı giriş tabelası gece randevu trafiğinde fark yaratır.",
        "İç yön ile İSG işaretleri karıştırılmamalıdır.",
    ],
    "plaza-ofis": [
        "Plaza’da asansör ve güvenlik kuralları uygulama penceresini belirler.",
        "Resepsiyon duvarı premium algı için lightbox veya sade panel olabilir.",
        "Kat içi cam işaretleri aşırıya kaçmadan tutulmalıdır.",
        "Yönetim onayı olmayan cephe işi risklidir; keşifte sorulur.",
        "Ofis paketleri aşamalı teslim edilebilir.",
    ],
    "insaat-santiye": [
        "Şantiye tabelası çoğu zaman geçicidir; kalıcı malzeme israfı yapılmamalıdır.",
        "Rüzgâr ve toz panoları erken yıpratır; yenileme bütçesi konuşulur.",
        "Uyarı eksikliği saha güvenliğini etkiler; İSG seti ayrıca ele alınır.",
        "Proje bitiminde söküm ve atık sorumluluğu netleştirilir.",
        "Kalıcı tesis kimliği için totem/tabela ayrı fazda planlanabilir.",
    ],
    "perakende": [
        "Cadde mağazasında ilk 3 saniye okunurluk satışa açılan kapıdır.",
        "Açılış paketinde ışıklı + vitrin birlikte planlanırsa aksama riski düşer.",
        "Kampanya folyosu haftalık değişiyorsa malzeme sınıfı buna göre seçilir.",
        "İç display, cephe tabelasının yerini tutmaz.",
        "Zincir mağazalarda şablon standardı hız kazandırır.",
    ],
}

ARTICLE_EXPAND = {
    "tabela-cesitleri": [
        "Çeşit seçerken ‘en pahalı = en iyi’ yaklaşımı işe yaramaz; okuma koşulu belirleyicidir.",
        "İç mekân bilgilendirme ile dış cephe aynı kategoride toplanmamalıdır.",
        "Karşılaştırmayı hizmet satış sayfasına taşımak ownership’i bozar; burada eğitim kalır.",
        "Birden fazla tip aynı cephede kullanılacaksa hiyerarşi çizilir: ana kimlik + destek yüzey.",
        "Bakım maliyeti ilk yatırım kadar önemlidir; LED’li sistemlerde servis katmanı vardır.",
        "Yanlış tür seçimi montajdan sonra pahalıya yenilenir.",
    ],
    "isikli-mi-isiksiz-mi": [
        "Gece kapalı işletmede ışıklı yatırım çoğu zaman ertelenebilir.",
        "Yarı gece açık noktalarda düşük yoğunluklu LED yeterli olabilir.",
        "Maliyet farkı sadece LED değil; kasa, elektrik ve servistir.",
        "Işıksız seçip sonradan LED eklemek her zaman mümkün olmayabilir.",
        "Lightbox karşılaştırması retail içi ihtiyaçlar içindir.",
        "Karar matrisini yazıp hizmet sayfasına geçmek en temiz yoldur.",
    ],
    "kutu-harf-malzemeler": [
        "Pleksi ışıklı harfte renk kontrolü kolaydır; dış çizilmeye karşı temizlik önemli.",
        "Paslanmaz mimari dil ister; her cepheye uymayabilir.",
        "Işıklı/ışıksız kararını malzemeden önce vermek süreci hızlandırır.",
        "Montaj yüzeyi fotoğrafı olmadan malzeme önerisi eksik kalır.",
        "Channel letters terimi ayrı ürün vaadi değildir.",
        "Bakımda kimyasal seçimi yüzey tipine göre değişir.",
    ],
    "one-way-vision-nedir": [
        "OWV, tam opak folyonun alternatifi olarak görüşü korur.",
        "İçerisi karanlık, dışarısı aydınlıkken denge bozulabilir.",
        "Uygulama hataları çoğunlukla kirli cam ve yanlış gergiden gelir.",
        "Kampanya bitiminde söküm iz bırakmadan planlanmalıdır.",
        "Araç uygulaması bina vitrininden farklı kurallara tabidir.",
        "Satın alma kararı Cam Giydirme sayfasında tamamlanır.",
    ],
    "arac-giydirme-rehberi": [
        "Full wrap marka alanını maksimize eder ama bütçe ve süre ister.",
        "Parça giydirme çoğu KOBİ filosunda yeterlidir.",
        "Yıkama alışkanlığı ömrü belirler; operasyona anlatılmalıdır.",
        "Filoda araç tipi çeşitliliği şablon sayısını artırır.",
        "Söküm sonucu araç boyasına göre değişir; genel garanti cümlesi yoktur.",
        "Ticari adım Araç Giydirme hizmet URL’sidir.",
    ],
    "tabela-fiyati": [
        "m² fiyatı tek başına yanıltıcıdır; montaj ve ışık katmanı eklenir.",
        "Keşifsiz verilen rakam bağlayıcı teklif değildir.",
        "Yerel fiyat bağlamı keşif sonrası konuşulur.",
        "Toplu işlerde birim düşebilir; oran peşin ilan edilmez.",
        "En ucuz teklif çoğu zaman eksik kapsam taşır.",
        "Bu sayfa eğitimdir; sipariş hizmet veya WhatsApp ile yürür.",
    ],
    "totem-secim-rehberi": [
        "Yaklaşım yönü tek taraflı veya çift taraflı yüzeyi belirler.",
        "Hızlı yolda okuma süresi kısadır; mesaj sade tutulur.",
        "Temel ve izin kalemleri ‘sürpriz maliyet’ olmasın diye başta sorulur.",
        "Indoor display seçim kriterleri burada değildir.",
        "Işıklı totem gece lojistik girişlerinde anlamlıdır.",
        "Sipariş Totem hizmet sayfasından ilerler.",
    ],
}

SERVICE_EXPAND2 = {
    "tabela": [
        "Montaj yüksekliği arttıkça iskele veya vinç ihtiyacı doğabilir; bu kalem keşifte görünür.",
        "Marka kılavuzu yoksa sade, yüksek kontrastlı bir düzen önerilir; abartılı efektler okumayı bozabilir.",
        "Aynı cephede birden fazla tabela varsa ana kimlik ile destek yüzey ayrılır.",
        "Teslim sonrası ek tabela talepleri mevcut montaj noktaları üzerinden hızlanabilir.",
        "Tekirdağ’daki tabela işleri için yerel hizmet sayfamıza bakabilirsiniz.",
    ],
    "isikli-tabela": [
        "Elektrik hazır değilse altyapı işi teklife ayrı satır olarak yazılır.",
        "Servis kapağı olmayan kasa uzun vadede maliyeti artırır.",
        "Cephe rengi LED algısını değiştirir; mock-up veya örnek ton konuşulabilir.",
        "Gece fotoğrafı yokken ‘çok parlak olacak’ iddiası yürütülmez.",
        "Tekirdağ’da ışıklı tabela için yerel sayfamıza bakın.",
    ],
    "kutu-harf": [
        "Harf aralıkları (kerning) uzaktan okumayı etkiler; sıkışık yazı tercih edilmez.",
        "Işıklı modelde trafo konumu estetik ve servis için planlanır.",
        "Taş veya tuğla cephede dübel seçimi keşif notuna işlenir.",
        "Tekirdağ plaza işleri için yerel kutu harf sayfamıza bakabilirsiniz.",
        "Üretim öncesi onaylı görsel olmadan kesim başlamaz.",
    ],
    "totem": [
        "Çift yüzlü totem iki yönlü yaklaşımda anlamlıdır; tek yön yetiyorsa maliyet düşer.",
        "Zemin altı engel (kablo, boru) riski keşifte sorulur.",
        "Grafik alanı ileride değişecekse manyetik/vidalı panel düşünülür.",
        "İzin süreçleri müşteri veya site yönetimine bağlıdır; süre garanti edilmez.",
        "Yerel niyet /hizmet-bolge/tekirdag-totem/ altındadır.",
    ],
    "arac-giydirme": [
        "Araç tesliminden önce yıkama ve kuru yüzey şarttır.",
        "Cam filmleri görüş güvenliğini bozmuyorsa uygulanır; yasal sınırlar müşteri sorumluluğundadır.",
        "Filo teslimatı araç araç yapılabilir; tek seferde bitirme vaadi yok.",
        "Tasarımda plaka ve cam alanları boş bırakılır.",
        "Tekirdağ filo işleri için yerel araç giydirme sayfamıza bakabilirsiniz.",
    ],
    "cam-giydirme": [
        "Baskı çözünürlüğü vitrin mesafesine göre seçilir.",
        "Güneşe bakan cephede solma riski konuşulur; mucize vaadi yok.",
        "Kapı camında açılır-kapanır tolerans bırakılır.",
        "Ofis gizlilik paketleri Ofis Branding ile birlikte yönetilebilir.",
        "Tekirdağ cam giydirme için yerel sayfamıza bakabilirsiniz.",
    ],
    "lightbox": [
        "Görsel dosyası renk profili bozulmadan istenmelidir.",
        "Asma tavan veya alçıpan taşıma kapasitesi keşifte kontrol edilir.",
        "Sürekli açık lightbox’ta ısı yönetimi konuşulur.",
        "Kumaş stoğu müşteriye teslim edilmezse sonraki değişim için saklama planı yapılır.",
        "Keşif Tekirdağ üssünden planlanır.",
    ],
    "display-pos": [
        "Taşıma çantası ve yedek ayak gibi aksesuarlar pakete eklenebilir.",
        "Dış mekân kısa süreli kullanımda rüzgâr riski vardır.",
        "Baskı prooflu onay büyük adetlerde hatayı azaltır.",
        "Depolama nemi baskıyı bozabilir; müşteriye not düşülür.",
        "Kalıcı cephe ihtiyacı Tabela/Totem’e yönlendirilir.",
    ],
    "ofis-branding": [
        "Koridor uzunsa işaret sıklığı abartılmadan planlanır.",
        "Camda marka + yön birlikte verilecekse hiyerarşi kurulur.",
        "Renkler marka kılavuzundan sapmadan tutulur.",
        "Uygulama sonrası yapışkan gazı için havalandırma önerilebilir.",
        "Kanıt için proje sayfalarına gerçek fotoğraf bağlanır.",
    ],
    "is-guvenligi-tabelalari": [
        "Saha listesi eksikse üretim eksik kalır; liste müşteriden istenir.",
        "Çok dilli ihtiyaç varsa metin onayı çift dilde alınır.",
        "Fosforlu/reflektif seçenekler gece saha için ayrıca konuşulur.",
        "Yanlış konumlandırılmış acil çıkış işaretini düzeltmek yeniden keşif ister.",
        "Uydurma denetim veya belge hizmeti sunulmaz.",
    ],
}
SERVICE_LONG = {
    "tabela": "Tabela projesinde başarı; doğru yüzey, doğru mesaj hiyerarşisi ve güvenli montajın toplamıdır. Malt Studio bu üçlüyü Tekirdağ üssünden yönetir: keşif notları üretime, üretim sahaya bağlanır. Stok tabela yerine ölçüye özel imalat tercih edilir çünkü her cephe aynı aparat ve dayanım ihtiyacını taşımaz. Fiyat tarafında internet listesi yoktur; ölçü, malzeme, yükseklik ve lojistik keşif sonrası yazılı teklife döner. Bakımda periyodik temizlik ve bağlantı kontrolü yeterlidir; garanti kapsamı teklifte netleşir. Kanıt için proje sayfalarına gerçek fotoğraf eklenene kadar uydurma metrik yazılmaz. Yenileme işlerinde söküm ve yüzey rötuşu ayrıca konuşulur. Kurumsal zincirlerde şablon standardı hız kazandırabilir; tek noktada ise ölçüye özel çözüm öne çıkar. İç bilgilendirme ile dış cephe aynı brief’te karıştırılmaz. Montaj yüksekliği iskele veya vinç ihtiyacını doğurabilir. Teslimde hizalama ve kenar bitiş kontrol edilir. Tekirdağ + tabela niyeti S×C sayfasındadır.",
    "isikli-tabela": "Işıklı tabela bir aydınlatma ürününden çok, gece okunan bir kimlik sistemidir. Kasa, LED, güç kaynağı ve yüzey birlikte çalışmazsa sonuç ya karanlık ya da rahatsız edici parlak olur. Keşifte elektrik hattı, servis kapağı ve cephe derinliği not edilmeden üretim başlatılmaz. Neon vaadi veya abartılı ömür yılı eklenmez; konuşulan gerçek bileşenlerdir. Montaj sonrası mümkünse gece kontrolü yapılır; değilse bağlantı ve sızdırmazlık teslim kriteridir. Serviste önce güç ve bağlantı bakılır. Dış mekânda su-toz riski conta ve drenaj detayıyla yönetilir. Aşırı LED yoğunluğu hem komşuyu rahatsız eder hem okumayı bozar. Elektrik hazır değilse altyapı kalemi teklife yazılır. Mağaza, klinik ve plaza girişleri tipik kullanım alanlarıdır. Bakımda aşındırıcı kimyasal önerilmez. Acil arızada kapasiteye göre müdahale planlanır; tutulmayan süre vaadi verilmez.",
    "kutu-harf": "Kutu harf, markayı cepheye üç boyutlu taşır; font, aralık ve derinlik okunurluğu doğrudan etkiler. Pleksi ve paslanmaz yolları karşılaştırmalı anlatılır ama nihai seçim mimari ve bütçeyle keşifte netleşir. Channel letters ayrı URL değildir. Işıklı modelde LED ve trafo planı estetik kadar servisi de belirler. Cam veya taş cephede aparat planı yoksa iş risklidir. Üretim onaylı görsele bağlanır; onaysız kesim yapılmaz. Ofis içi 3D logo ihtiyacı ofis branding paketiyle birleştirilebilir. Harf yüksekliği gösteriş için şişirilmez; okuma mesafesine göre seçilir. Paslanmazda montaj izinin mimariye uyumu konuşulur. Tek harf hasarında tüm yazıyı sökmek çoğu zaman gerekmez. Font lisansları müşteri sorumluluğundadır. Bakımda yumuşak temizlik ve ışıklı modellerde servis erişimi korunur. Plaza ve mağaza cepheleri en sık uygulama alanlarıdır.",
    "totem": "Totem işi üretim kadar saha lojistiğidir. Yükseklik, görüş açısı, zemin ve varsa ışıklı ihtiyaç keşifte birlikte okunur. Pylon adı aynı ailede kalır; indoor display ayrıdır. Temel ve izin konuları uydurma mühendislik iddiası olmadan, keşif sonrası konuşulur. OSB girişlerinde araç trafiği montaj penceresini belirler. Grafik paneli değişebilir bırakılırsa ileride yenileme kolaylaşır. Çift yüzlü totem iki yönlü yaklaşımda anlamlıdır. Zemin altı engel riski sorulur. Işıklı totemlerde servis erişimi tasarımda bırakılır. Bakımda bağlantı ve LED kontrolü periyodik önerilir. Yol kenarı mesajı sade tutulur çünkü okuma süresi kısadır. Bu sayfa sabit dış/tesis totemine odaklanır. Display & POS taşınabilir ihtiyaçlar içindir.",
    "arac-giydirme": "Araç giydirme mobil bir marka yüzeyidir; başarı yüzey hazırlığı ve doğru folyo sınıfına bağlıdır. Full wrap her filoda zorunlu değildir. Parça giydirme çoğu senaryoda yeterlidir. Boya durumu söküm sonucunu etkiler; genel ‘boya bozulmaz’ vaadi verilmez. Filoda şablon standardı hız kazandırır ama araç tipi çeşitliliği şablon sayısını artırır. Uygulama sıcaklığı uygun değilse iş ertelenir. Yıkama alışkanlığı ömrü belirler; kenara yüksek basınç zarar verebilir. Tasarımda plaka ve cam sınırları boş bırakılır. Araç tesliminden önce kuru ve temiz yüzey şarttır. Cam filmlerinde yasal sınırlar müşteri sorumluluğundadır. Filo teslimatı araç araç yapılabilir. Bina camı bu sayfanın konusu değildir. Hasarlı panel şablondan yenilenebilir.",
    "cam-giydirme": "Cam giydirme görünürlük ile gizlilik arasında denge kurar. OWV, frosted ve opak yolları ihtiyaca göre seçilir; her vitrin aynı reçeteyi istemez. Kirli cam ve kötü gergi en sık hata kaynağıdır. Kampanya yüzeyi sabit tabela gibi düşünülmez. Plaza kuralları yapışkan tipini kısıtlayabilir. Temizlikte aşındırıcı sünger kullanılmaz. Ofis gizlilik paketleri ofis branding ile birlikte yönetilebilir. Araç camı filo işlerinde araç giydirme kapsamına girer. Delik oranı iç aydınlatmayı etkiler. Kapı camında açılır-kapanır tolerans bırakılır. Baskı çözünürlüğü görüş mesafesine göre seçilir. Güneşe bakan cephede solma riski konuşulur; mucize vaadi yok. Kampanya bitiminde kontrollü söküm planlanır.",
    "lightbox": "Lightbox, ışıklı kutu/frame ailesidir ve cephe LED tabeladan bilinçli ayrılır. SEG ve backlit fabric hızlı görsel değişim ister. Kasa tipi mekân, elektrik ve askı yöntemine göre seçilir. AVM kuralları saat ve malzemeyi etkileyebilir. Kumaş gergisi bozulursa ışık lekesi oluşur. Serviste kumaş değişimi ile LED değişimi ayrı kalemlerdir. Görsel dosyası renk profili korunarak istenmelidir. Asma tavan taşıma kapasitesi keşifte kontrol edilir. Sürekli açık sistemlerde ısı yönetimi konuşulur. Resepsiyon duvarında ofis branding ile birlikte planlanabilir. Uydurma stok adedi veya sahte ömür yılı eklenmez. Mağaza içi, showroom ve klinik bekleme tipik alanlardır. Yanlışlıkla cephe tabela talebi Işıklı Tabela’ya yönlendirilir.",
    "display-pos": "Display ve POS kısa–orta ömürlü görünürlük içindir. Kalıcı outdoor totem buraya zorlanmaz. Malzeme sınıfı kullanım süresine göre seçilir; fuar ile mağaza içi farklıdır. Tekrarlayan kampanyalarda şablon saklanır. Roll-up mekanikleri taşımaya hassastır. Adet arttıkça birim maliyet düşebilir ama peşin oran ilan edilmez. Şantiye panolarında söküm planı baştan konuşulur. Taşıma çantası ve yedek ayak pakete eklenebilir. Dış mekân kısa kullanımda rüzgâr riski vardır. Baskı prooflu onay büyük adetlerde hatayı azaltır. Depolama nemi baskıyı bozabilir. Yanlışlıkla cephe tabela talebi gelirse Tabela veya Totem’e yönlendirilir. Amaç satış anında veya etkinlikte hızlı kurulan yüzeyi sağlamaktır. Uydurma stok adedi yazılmaz.",
    "ofis-branding": "Ofis branding workplace’te tutarlı ilk izlenim üretir. Resepsiyon, cam ve koridor işaretleri aynı dilde tutulur; aşırı logo tekrarı zayıflatır. Plaza yönetimi onayı takvimi etkiler. Cam folyo malzemesi cam giydirme ile paylaşılır, paket burada yönetilir. Mesai içi kesinti riski varsa alternatif pencere sunulur. Kapı isimlikleri opsiyoneldir. Koridor uzunsa işaret sıklığı abartılmaz. Renkler marka kılavuzundan sapmadan tutulur. Uygulama sonrası yapışkan kokusu için havalandırma önerilebilir. Kanıt proje sayfalarına gerçek fotoğrafla bağlanır; uydurma ofis sayısı yazılmaz. İç mekân için yeni URL açılmaz. Kutu harf ihtiyacı varsa ilgili hizmetle birlikte aşamalandırılır. Klinik ve plaza ofisleri sakin dil ister.",
    "is-guvenligi-tabelalari": "İş güvenliği tabelaları uyarı ve acil durum işaretleridir; wayfinding değildir. Belgelendirme kuruluşu olunmaz, uydurma uygunluk belgesi eklenmez. Saha listesi müşteriden alınır; liste yoksa üretim eksik kalır. Acil çıkış konumları görüş hattına göre onaylanır. Dış mekânda dayanım sınıfı yükseltilir. Reflektif ihtiyaç gece harekete göre konuşulur. Toplu setlerde standartlaşma hız kazandırır. Mevzuat takibi müşteri tarafındadır; tabela üreticisi danışman değildir. Çok dilli ihtiyaçta metin onayı çift dilde alınır. Yanlış konumlandırılmış işaret düzeltmesi yeniden keşif ister. Fabrika, depo ve şantiye tipik sahalardır. Yangın çıkışı bu ailededir. Soluma ve darbede tekil değişim planlanır.",
}

INDUSTRY_LONG = {
    "fabrika-osb": "Fabrika ve OSB dikeyinde görünürlük çoğu zaman tek ürün değildir. Kapı totemi, cephe yazısı, iç yön ve İSG seti aynı marka dilinde okunmalıdır. Ağır araç trafiği montaj güvenliğini etkiler. Tozlu ortam malzeme sınıfını yükseltebilir. Filo giydirme tesis tabelasıyla kopuksa saha algısı bölünür. İSG yenilemesi duruş planına bağlanır. Vinç ve OSB giriş kuralları teklife yansır. Bu sayfa dikey giriştir; satın alma ilgili hizmet URL’lerindedir. Uydurma tesis sayısı veya sahte uygunluk belgesi eklenmez. Keşif Tekirdağ üssünden planlanır.",
    "restoran-cafe": "Restoran ve cafe dikeyinde cephe ile vitrin birlikte çalışır. Gece açık işletmede ışıksız kimlik çoğu zaman yetersiz kalır. Vitrin kampanyası sabit tabeladan ayrı yenilenmelidir. Aşırı kalabalık grafik ürün yerine gürültü üretir. Mutfak çevresinde iç yüzey seçimi yağ buharını dikkate alır. Montaj penceresi servis saatlerine göre seçilir. Lightbox iç anlatım için opsiyoneldir. Kanıt proje sayfalarına gerçek fotoğrafla bağlanır.",
    "saglik": "Sağlık dikeyinde sakin dil güveni korur. Agresif kampanya dili zedeler. Giriş ışıklı tabela gece randevu trafiğinde işe yarar. Bekleme alanı tıbbi iddia taşımaz. Hijyen kuralları temizlik rejimini etkiler. Camda hafif frosted tercih edilebilir. İSG ile yön işaretleri karıştırılmaz. Uydurma klinik sayısı yazılmaz.",
    "plaza-ofis": "Plaza ve ofiste ilk izlenim resepsiyon ve cephede kurulur. Yönetim onayı takvimi belirler. Kutu harf, cam ve ofis branding aşamalı teslim edilebilir. Koridor işaretleri abartılmadan planlanır. Lightbox premium katman olabilir. Mesai dışı uygulama kesintiyi azaltır. Bu sayfa dikeydir; sipariş hizmet URL’lerindedir.",
    "insaat-santiye": "Şantiye dikeyinde geçici ve kalıcı ihtiyaç ayrılır. Geçici panoda aşırı pahalı malzeme israftır. Rüzgâr ve toz panoları yıpratır. Uyarı eksikliği İSG setiyle kapatılır. Proje bitiminde söküm konuşulur. Kalıcı tesis kimliği ayrıca fazlanır. Display kısa süreli, totem daha kalıcıdır. Uydurma şantiye metriği yok.",
    "perakende": "Perakendede cadde kotunda ilk okuma kritiktir. Açılışta ışıklı ve vitrin birlikte planlanır. Kampanya folyosu sık yenileniyorsa malzeme buna göre seçilir. İç display cephe yerine geçmez. Zincirlerde şablon hız kazandırır. Keşif sonrası net teklif verilir.",
}

ARTICLE_LONG = {
    "tabela-cesitleri": "Tabela çeşitleri rehberi eğitimdir. En pahalı seçenek her zaman doğru değildir. İç ve dış ihtiyaç aynı kategoride toplanmaz. Birden fazla tip varsa ana kimlik ve destek yüzey ayrılır. Bakım maliyeti ilk yatırıma eklenerek düşünülür. Yanlış tür sonradan pahalıya yenilenir. Sipariş /hizmetler/tabela/ altındadır. Lightbox ve ışıklı tabela bilinçli ayrılır. Keşif fotoğrafı karar kalitesini yükseltir.",
    "isikli-mi-isiksiz-mi": "Işıklı/ışıksız kararı işletme saatleriyle başlar. Gece kapalıysa LED yatırımı ertelenebilir. Maliyet farkı LED + kasa + elektrik + servistir. Sonradan LED eklemek her yapıda mümkün olmayabilir. Lightbox retail içi karşılaştırmadır. Karar sonrası doğru hizmet URL’sine geçilir. Abartılı ömür vaadi eğitim metninde yoktur.",
    "kutu-harf-malzemeler": "Malzeme karşılaştırması bilgilendirmedir. Pleksi ışık ve renk; paslanmaz dayanım ve prestij tarafındadır. Işıklı/ışıksız kararını malzemeden önce vermek süreci hızlandırır. Montaj yüzeyi fotoğrafı olmadan öneri eksik kalır. Channel letters ayrı ürün vaadi değildir. Sipariş kutu harf hizmetindedir.",
    "one-way-vision-nedir": "OWV görüşü koruyarak dışarıda mesaj taşır. İçerisi karanlıksa denge bozulabilir. Hata çoğu zaman kirli cam ve kötü gergiden gelir. Kampanya sökümü iz bırakmadan planlanır. Araç kuralları bina vitrininden farklıdır. Uygulama Cam Giydirme sayfasındadır.",
    "arac-giydirme-rehberi": "Full wrap alan maksimize eder; parça giydirme çoğu filoda yeter. Yıkama ömrü belirler. Araç tipi çeşitliliği şablon sayısını artırır. Söküm sonucu boyaya göre değişir. Ticari adım araç giydirme hizmetidir. Kış uygulaması sıcaklığa bağlıdır.",
    "tabela-fiyati": "m² fiyatı tek başına yanıltıcıdır. Keşifsiz rakam bağlayıcı değildir. Geo fiyat S×C bağlamında konuşulur. Toplu işte birim düşebilir; oran peşin ilan edilmez. En ucuz teklif eksik kapsam taşıyabilir. Bu sayfa eğitimdir.",
    "totem-secim-rehberi": "Yaklaşım yönü tek/çift yüzü belirler. Hızlı yolda mesaj sade tutulur. Temel ve izin sürpriz maliyet olmasın diye başta sorulur. Indoor display burada değildir. Işıklı totem gece lojistikte anlamlıdır. Sipariş totem hizmetindedir.",
}

SERVICE_LONG2 = {
    "tabela": "Keşif formunda ölçü, yüzey fotoğrafı, gece ihtiyacı ve erişim notları birlikte tutulur. Bu notlar hem atölyeyi hem montaj ekibini yönlendirir. Aynı markanın birden fazla şubesinde şablon kullanılacaksa tipik ölçü seti çıkarılır; yine de her cephe doğrulanır. Söküm gerektiren yenilemelerde eski bağlantı izleri ve boya durumu teklife yansıtılır. Acil tabela talepleri kapasiteye göre sıralanır. Üretim kalite kontrolünde ölçü sapması ve kenar bitiş kontrol edilir. Sahada su terazisi ve hizalama teslimin parçasıdır. Müşteri onayı olmadan görsel yayına alınmaz. Proje kanıtı geldikçe ilgili vaka URL’sine bağlanır.",
    "isikli-tabela": "Işıklı sistemlerde yedek güç kaynağı ihtiyacı konuşulabilir ama stok vaadi verilmez. Cephe rengi ve ambient ışık LED algısını değiştirir. Servis sözleşmesi ayrı bir kalem olabilir; peşin ‘ömür boyu’ ifadesi kullanılmaz. Montaj ekibi elektrik güvenliği kurallarına uyar. İç mekân ışıklı kutu ihtiyacı Lightbox’a yönlendirilir. Dış cephede kaçak riski conta detayıyla azaltılır. Teklifte kasa tipi, LED sınıfı ve montaj yüksekliği satır satır görünür. Onaysız üretim başlamaz.",
    "kutu-harf": "Kutu harfte renk eşlemesi marka koduna göre yapılır; ekran ile gerçek yüzey farkı konuşulur. Alüminyum yan band seçenekleri modele göre değişir. Yüksek cephede iskele planı önceden çıkarılır. Rüzgâr yükü büyük harflerde keşif notuna yazılır. İç mekân harflerde farklı yapışkan/montaj kullanılır. Teslimde tek tek harf sabitlemesi kontrol edilir. Revizyon isteği onay döngüsüne bağlanır.",
    "totem": "Totem grafik alanında az metin daha iyi okunur. Logo + yön oku sık pakettir. Temel kürü bekleme süresi takvime yazılır; mucize hızlı kurulum vaadi yok. Çevrede ağaç veya tabela perdesi varsa yükseklik yeniden değerlendirilir. Işıklı modelde gece test imkânı sorulur. Panel vidaları vandalizme karşı dayanıklı seçilebilir. Teslim tutanağı bağlantı ve dikeylik kontrolünü içerir.",
    "arac-giydirme": "Araç giydirmede marka renkleri baskı profiliyle doğrulanır. Kaput ve çamurluk gibi eğri alanlar ek süre isteyebilir. Filo araçları sırayla planlanır; aynı anda tüm filoyu bağlamak her zaman mümkün değildir. Uygulama sonrası ilk yıkama için bekleme süresi önerilir. Sökümde ısı ve doğru spatula kullanılır. Müşteri araç sigortası/işletme kuralları kendi sorumluluğundadır.",
    "cam-giydirme": "Cam giydirmede ek yerleri mümkün olduğunca görüş hattı dışına alınır. Büyük vitrinde panel planı önceden çizilir. Gece aydınlatması grafiğin okunmasını değiştirir. Kapalı gün uygulama kalitesini yükseltir. Folyo kenarlarında kabarcık kontrolü yapılır. Kampanya takvimi varsa baskı ve söküm slotları peşinen konuşulur.",
    "lightbox": "Lightbox görsellerinde güvenli alan (safe margin) bırakılır. Kumaş kırışıklığı teslim öncesi giderilir. Duvar tipi alçıpan ise ek taşıyıcı gerekebilir. Sürekli açık/kapalı senaryosu LED tipini etkiler. Müşteri görsel değişimini kendi yapacaksa kısa eğitim verilebilir. Magazin/AVM güvenlik prosedürlerine uyulur.",
    "display-pos": "Display işlerinde kargo hasarı riski ambalajla azaltılır. Kurulum gerektiren standlarda zemin tipi not edilir. Kısa süreli açık hava kullanımında su riski konuşulur. Baskı sonrası kuruma/laminasyon ihtiyacı modele bağlıdır. Müşteri deposunda saklama koşulları hatırlatılır. Yeniden baskı için kaynak dosya saklanır.",
    "ofis-branding": "Ofis keşfinde elektrik prizi, cam tipi ve güvenlik kartı erişimi not edilir. Renk örneği onaylanmadan toplu baskı yapılmaz. Sessiz alanlarda düşük gürültülü uygulama tercih edilir. Teslimde yapışma ve hizalama kontrol listesi işlenir. Ek oda talepleri aynı proje koduna bağlanabilir. Marka kılavuzu yoksa sade sistem önerilir.",
    "is-guvenligi-tabelalari": "İSG setinde piktogram netliği metinden önce gelir. Saha numaralandırması varsa listeyle eşleştirilir. Dış mekânda UV dayanımlı baskı konuşulur. Montaj yüksekliği görüş ve vandalizm dengesine göre seçilir. Eksik levha sonradan tamamlanabilir. Müşteri iç denetim checklist’i varsa ona göre set genişletilir. Danışmanlık ücreti veya belge satışı yoktur.",
}

SERVICE_CHECKLIST = {
    "tabela": [
        "Keşifte net ölçü alınmadan üretim veya bağlayıcı fiyat verilmez.",
        "Yüzey fotoğrafı aparat ve delik planını görünür kılar.",
        "Gece ihtiyacı varsa Işıklı Tabela sayfasına bilinçli geçiş yapılır.",
        "Lightbox talebi retail kutu ise bu sayfada tutulmaz.",
        "Montaj yüksekliği iskele veya vinç kalemini doğurabilir.",
        "Yenilemede söküm ve yüzey rötuşu ayrıca konuşulur.",
        "Site yönetimi kuralı varsa keşif notuna yazılır.",
        "Vektörel marka dosyası kaliteyi yükseltir; yoksa sade alternatif önerilir.",
        "İç bilgilendirme ile dış cephe brief’te ayrılır.",
        "Lojistik süresi koridor işlerinde teklife yansır.",
        "Bakım beklentisi garanti kapsamıyla birlikte netleştirilir.",
        "Teklif satırları ölçü, malzeme, montaj ve lojistiği ayırır.",
        "Onaylı görsel olmadan kesim/baskı başlamaz.",
        "Teslimde hizalama ve kenar bitiş kontrol edilir.",
                "Acil talepler kapasiteye göre sıralanır; tutulmayan süre vaadi yok.",
        "Ek tabela ihtimali varsa montaj noktaları buna göre düşünülür.",
        "Kanıt fotoğrafları proje sayfasına bağlanmak üzere planlanır.",
    ],
    "isikli-tabela": [
        "Gece işletme saati yoksa LED yatırımı bilinçli ertelenir.",
        "Elektrik hattı hazır değilse altyapı kalemi teklife yazılır.",
        "Servis kapağı olmayan kasa uzun vadede maliyeti artırır.",
        "Kasa derinliği LED tipi ve servisi birlikte belirler.",
        "LED yoğunluğu komşu ve okunurluk dengesiyle ayarlanır.",
        "Lightbox ihtiyacı bu sayfanın sahibi değildir.",
        "Dış mekânda sızdırmazlık detayı keşifte konuşulur.",
        "Gece testi mümkünse montaj sonrası yapılır.",
        "Trafo konumu estetik ve servis için planlanır.",
        "Cephe rengi LED algısını değiştirebilir.",
        "Montaj yüksekliği güvenlik planını etkiler.",
        "Servis modeli peşin ‘ömür boyu’ vaadi içermez.",
        "Onaylı görsel olmadan üretim başlamaz.",
        "Teklifte kasa, LED ve montaj satırları ayrılır.",
                "Acil arızada önce güç ve bağlantı kontrol edilir.",
        "Temizlik aşındırıcı kimyasalsız önerilir.",
        "Kanıt için gerçek gece/gündüz fotoğraf planlanır.",
    ],
    "kutu-harf": [
        "Okuma mesafesi harf yüksekliğini belirler; şişirme yapılmaz.",
        "Pleksi ve paslanmaz kararları mimariye göre verilir.",
        "Işıklı/ışıksız tercih üretimden önce netleşir.",
        "Vektörel logo/font kaliteyi yükseltir.",
        "Montaj yüzeyi aparat tipini belirler.",
        "Kerning uzaktan okumayı etkiler.",
        "LED’li modellerde trafo planı şarttır.",
        "Yüksek cephede iskele/vinç keşifle planlanır.",
        "Channel letters ayrı URL değildir.",
        "Ofis içi 3D logo ofis branding ile paketlenebilir.",
        "Tek harf servisi tüm yazıyı sökmeyi gerektirmeyebilir.",
        "Onaylı mock-up olmadan kesim başlamaz.",
        "Dış temizlik yumuşak yapılmalıdır.",
        "Renk kodu marka kılavuzundan sapmaz.",
                "Teslimde her harf sabitlemesi kontrol edilir.",
        "Font lisansı müşteri sorumluluğundadır.",
        "Kanıt fotoğrafı proje sayfasına bağlanır.",
    ],
    "totem": [
        "Yaklaşım yönü tek/çift yüz kararını belirler.",
        "Yükseklik görüş açısına göre seçilir.",
        "Temel ihtiyacı keşif sonrası netleşir.",
        "İzin riski peşinen sorulur; süre garanti edilmez.",
        "Işıklı ihtiyaç gece lojistiğe göre konuşulur.",
        "Indoor display bu sayfada çözülmez.",
        "Pylon aynı ailede anlatılır.",
        "Zemin altı engel riski sorulur.",
        "Grafik alanı az metinle tutulur.",
        "Vinç planı OSB kurallarına bağlanır.",
        "Değişebilir panel yenilemeyi kolaylaştırır.",
        "Teslimde dikeylik kontrol edilir.",
                "Bakım için LED/servis erişimi bırakılır.",
        "Mesaj sade tutulur çünkü okuma süresi kısadır.",
        "Rüzgâr perdesi varsa yükseklik yeniden değerlendirilir.",
        "Temel kürü takvime yazılır.",
        "Kanıt fotoğrafı planlanır.",
    ],
    "arac-giydirme": [
        "Full wrap zorunlu değildir; parça çoğu filoda yeter.",
        "Araç listesi ve fotoğraflar olmadan şablon çıkmaz.",
        "Yüzey durumu söküm sonucunu etkiler.",
        "Folyo sınıfı eğrilik ve süreye göre seçilir.",
        "Filo şablonu standart + araç uyarlamasıdır.",
        "Plaka ve cam alanları boş bırakılır.",
        "Uygulama sıcaklığı uygun değilse iş ertelenir.",
        "Filo takvimi araç araç ilerleyebilir.",
        "Yıkamada kenara yüksek basınç önerilmez.",
        "Sökümde kontrollü yöntem hedeflenir.",
        "Boya bozulmaz genel vaadi verilmez.",
        "Bina camı cam giydirme sayfasındadır.",
        "Baskı prooflu onay hatayı azaltır.",
        "Kenar kontrolü teslim kriteridir.",
                "Hasarlı panel şablondan yenilenir.",
        "İşletme/sigorta kuralları müşteriye aittir.",
        "Kanıt fotoğrafı planlanır.",
    ],
    "cam-giydirme": [
        "OWV, frosted ve opak ihtiyaçla seçilir.",
        "Cam ölçüleri keşifte doğrulanır.",
        "İç aydınlatma OWV dengesini etkiler.",
        "Kampanya yüzeyi sabit tabela değildir.",
        "Plaza yapışkan kuralları sorulur.",
        "Kapı camında tolerans bırakılır.",
        "Aşındırıcı temizlik önerilmez.",
        "Söküm kampanya bitiminde planlanır.",
        "Araç camı filo işinde araç giydirmededir.",
        "Ek yerleri görüş hattı dışına alınır.",
        "Mesaj hiyerarşisi sade tutulur.",
        "Ofis gizlilik paketi ofis branding ile yönetilebilir.",
        "Onaylı görsel olmadan baskı başlamaz.",
        "Kapalı gün uygulama kalitesini yükseltir.",
                "Solma riski konuşulur; mucize vaadi yok.",
        "Baskı çözünürlüğü mesafeye göre seçilir.",
        "Kanıt fotoğrafı planlanır.",
    ],
    "lightbox": [
        "Cephe LED tabela ihtiyacı Işıklı Tabela’yadır.",
        "SEG veya akrilik yüz mekâna göre seçilir.",
        "Duvar taşıma kapasitesi kontrol edilir.",
        "Elektrik noktası keşifte doğrulanır.",
        "Görselde safe margin bırakılır.",
        "AVM kuralları saat ve malzemeyi etkiler.",
        "Kumaş değişim sıklığı malzeme kararını etkiler.",
        "İnce kasa isteği servisle dengelenir.",
        "LED servis erişimi tasarımda bırakılır.",
        "Renk profili bozulmadan dosya istenir.",
        "Asma planı onaysız uygulanmaz.",
        "Ofis branding ile paketlenebilir.",
                "Teslimde gergi ve ışık homojenliği kontrol edilir.",
        "Uydurma stok adedi yazılmaz.",
        "Müşteri değişimi yapacaksa kısa eğitim verilebilir.",
        "Sürekli açık senaryosu LED tipini etkiler.",
        "Kanıt fotoğrafı planlanır.",
    ],
    "display-pos": [
        "Kalıcı outdoor totem Totem sayfasınadır.",
        "Kullanım süresi malzeme sınıfını belirler.",
        "İç/dış ortam ayrımı başta yapılır.",
        "Büyük adette baskı proof istenir.",
        "Kargo hasarı ambalajla azaltılır.",
        "Kurulum gerektiren standlarda zemin tipi not edilir.",
        "Açık havada rüzgâr riski konuşulur.",
        "Depolama nemi hatırlatılır.",
        "Tekrarlayan işte şablon saklanır.",
        "Roll-up taşıma hassasiyeti anlatılır.",
        "Şantiye panolarında söküm planı vardır.",
        "Aksesuarlar pakete eklenebilir.",
        "Cephe tabela talebi ilgili hizmete yönlenir.",
        "Teklif kalemleri net yazılır.",
        "Yeniden baskı için kaynak dosya tutulur.",
        "Fuar ve mağaza içi farklı reçetelerdir.",
        "Uydurma stok adedi yoktur.",
        "Kanıt fotoğrafı planlanır.",
    ],
    "ofis-branding": [
        "Plaza yönetimi onayı takvimi etkiler.",
        "Alan listesi olmadan paket çıkmaz.",
        "Cam folyo ile kutu harf ihtiyaçları ayrılır.",
        "Mesai penceresi kesintiye göre seçilir.",
        "Marka kılavuzu yoksa sade sistem önerilir.",
        "Aşırı logo tekrarı engellenir.",
        "Kapı isimliği opsiyonel kalemdir.",
        "Saf cam uygulaması cam giydirme ile paylaşılabilir.",
        "Renk örneği onayı toplu baskıdan önce alınır.",
        "Gürültü riski olan alanlar planlanır.",
        "Yeni iç mekân URL’si açılmaz.",
        "Teslim kontrol listesi işlenir.",
        "Ek oda talepleri aynı hatta bağlanır.",
        "Lightbox resepsiyonda opsiyoneldir.",
        "Vektörel logo kaliteyi yükseltir.",
        "Yapışkan kokusu için havalandırma önerilebilir.",
        "Uydurma ofis metriği yazılmaz.",
        "Kanıt fotoğrafı planlanır.",
    ],
    "is-guvenligi-tabelalari": [
        "Saha listesi yoksa üretim eksik kalır.",
        "Wayfinding bu ailenin H1’i değildir.",
        "Acil çıkış konumları müşteri onayıyla işlenir.",
        "Uygunluk belgesi vaadi verilmez.",
        "Dış mekânda dayanım sınıfı yükseltilir.",
        "Reflektif ihtiyaç gece harekete göre konuşulur.",
        "Piktogram netliği metinden önce gelir.",
        "Çok dilli metinler çift onay ister.",
        "Montaj yüksekliği görüş ve vandalizme göre seçilir.",
        "Toplu setlerde standartlaşma hız kazandırır.",
        "Mevzuat takibi müşteri tarafındadır.",
        "Eksik levha sonradan tamamlanabilir.",
        "Şantiye ve fabrika reçeteleri ayrılabilir.",
        "UV dayanımlı baskı dış için konuşulur.",
        "Danışmanlık veya belge satışı yoktur.",
        "Teslim liste eşleşmesiyle yapılır.",
        "Soluma/darbede tekil değişim planlanır.",
        "Kanıt fotoğrafı planlanır.",
    ],
}

SERVICE_NUDGE = {
    "cam-giydirme": "Cam giydirme tesliminden sonra ilk temizlik yumuşak bezle yapılmalıdır. Fitil kenarlarına su baskısı uygulanmaz. Kampanya grafikleri sabit tabela gibi bırakılmaz; bitiş tarihi varsa söküm slotu peşinen konuşulur. Showroom camlarında ürün görünürlüğü ile marka mesajı dengelenir. Tekirdağ vitrin işleri yerel S×C sayfasıyla desteklenir.",
    "display-pos": "Display ve POS tesliminde kurulum kılavuzu kısa tutulur. Mekanik aksamlar taşımada ayrı korunur. Mağaza içi yerleşimde yangın çıkışı ve koridor genişliği engellenmez. Sezon sonunda söküm veya depolama seçenekleri konuşulur. Kalıcı dış tabela ihtiyacı bu paketin parçası değildir ve ilgili hizmete yönlendirilir. Baskı renkleri mağaza aydınlatmasına göre kontrol edilir. Tekrar siparişte önceki şablon referans alınır. Açılış günü kurulum penceresi peşinen rezerve edilir. Yedek baskı adedi opsiyonel kalem olarak teklife yazılabilir.",
    "is-guvenligi-tabelalari": "İSG tabela montajında delik ve dübel seçimi yüzey tipine göre yapılır. Solmuş levhalar tekil değiştirilebilir. Acil durum işaretleri başka yön tabelalarıyla karıştırılmaz. Saha denetim öncesi eksik kontrol listesi müşteriye bırakılabilir. Üretim hızı liste netliğine bağlıdır. Çok dilli ihtiyaçta metinler ayrı onaylanır. Dış setlerde bağlantı korozyona karşı seçilir. Yangın çıkışı görüş hattı engellenmeden yerleştirilir. Toplanma alanı işaretleri gerektiğinde listeye ayrıca eklenir.",
    "lightbox": "Lightbox tesliminde uzaktan kumanda veya sensör istenirse ayrıca konuşulur; standart varsayılmaz. Kumaş yedek baskı opsiyoneldir. Duvar arkası kablo gizliği keşifte planlanır. Retail değişim sıklığı yüksekse SEG avantajı tekrar hatırlatılır.",
    "ofis-branding": "Ofis tesliminde yapışkan artığı ve hizalama sapması kontrol edilir. Yeni çalışan karşılama yüzeyleri sonradan eklenebilir. Marka renkleri monitör ile gerçek yüzey farkı için örnekle doğrulanır. Plaza ortak alan kuralları ihlal edilmez. Sessiz alanlarda düşük gürültülü uygulama tercih edilir. Toplantı odası camlarında sade yön ve isim hiyerarşisi korunur.",
}

SERVICE_BRIDGE = {
    "arac-giydirme": "Araç giydirme sürecinde tasarım onayı ile uygulama günü arasında baskı ve folyo hazırlığı vardır. Bu sürede araçların işletmeden çekileceği saatler netleştirilir. Panelvan, kamyonet ve binek kasa tipleri farklı şablon ister. Filo standardı marka alanlarını sabitlerken kapı tutacakları ve ayna dipleri araç özelinde uyarlanır. Uygulama sonrası kenar kaldırma riskini azaltmak için ilk günlerde otomatik yıkama önerilmez. Söküm planı baştan konuşulursa sonraki dönem yenilemesi daha öngörülebilir olur. Tekirdağ üssü filo işlerini planlı takvimle yönetir; uydurma ‘aynı gün tüm filo’ vaadi verilmez. Kanıt görselleri onaylandıkça proje sayfalarına eklenir.",
    "cam-giydirme": "Cam giydirme işinde başarı çoğu zaman baskıdan çok uygulamadadır. Toz, yağ filmi ve fitil kenarları hataları gizler. Büyük vitrinlerde panel planı önceden çizilmeden işe başlanmaz. Kampanya dönemlerinde sök-tak döngüsü için malzeme sınıfı baştan seçilir. Ofis camlarında mahremiyet ile marka dengesi brief’te yazılır. Gece vitrin aydınlatması grafiği farklı okutabilir; mümkünse akşam kontrolü yapılır. Tekirdağ mağaza vitrinleri S×C sayfasıyla yerel niyete bağlanır. Uydurma metrekare fiyatı veya stok görsel kullanılmaz. Teslimde kenar kabarcığı ve ek yeri kontrol edilir. Kampanya slotu peşinen planlanırsa aksama riski düşer. Kapı camında açılır-kapanır tolerans bırakılır.",
    "display-pos": "Display ve POS üretiminde hız önemlidir ama dayanım sınıfı kullanım süresine göre seçilmeden hızlandırılmaz. Fuar standı ile mağaza içi shelf talker aynı reçete değildir. Taşıma ve kurulum adımları brief’e yazılır. Açık hava kısa kullanımında ıslanma ve rüzgâr riski müşteriye anlatılır. Tekrarlayan kampanyalarda baskı şablonu saklanır; kaynak dosya kaybolursa yeniden iş bedeli doğabilir. Kalıcı cephe veya tesis totemi talebi geldiğinde Totem/Tabela sayfalarına yönlendirilir. Uydurma stok ve sahte adet yazılmaz. Kurulumda zemin tipi not edilir. Yeniden baskı için kaynak dosya saklanır. Ambalaj kargo hasarını azaltmak için güçlendirilir. Kısa ömürlü işte ‘ömür garantisi’ beklenmez.",
    "is-guvenligi-tabelalari": "İSG tabela setlerinde listenin doğruluğu üretimin yarısıdır. Eksik veya yanlış konumlandırılmış acil çıkış işaretleri sahada güvenliği zedeler. Bu yüzden yerleşim onayı olmadan rastgele asım yapılmaz. Reflektif ihtiyaç gece forklift trafiğine göre konuşulur. Dış mekân setlerinde UV ve darbe dayanımı yükseltilir. Malt Studio belge satmaz; üretim ve montaj yapar. Wayfinding talepleri bu sayfanın H1’ine zorlanmaz. Kanıt fotoğrafları onaylandıkça ilgili proje veya sektör sayfalarına bağlanır. Teslim liste eşleşmesiyle yapılır. Piktogram netliği metinden önce gelir. Eksik levha sonradan tamamlanabilir. Danışmanlık ücreti satılmaz.",
    "lightbox": "Lightbox projelerinde mekân ölçüsü, askı yöntemi ve görsel değişim sıklığı birlikte okunur. SEG tercihinde kumaş gergisi teslim kalitesinin göstergesidir. AVM veya plaza kuralları montaj saatini kısıtlayabilir. Cephe LED tabela isteyen müşteri bilinçli biçimde Işıklı Tabela’ya yönlendirilir; bu ayrım hem kullanıcıyı hem ownership’i korur. Ayrı S×C olmadığı için yerel keşif city hub üzerinden planlanır. Servis kalemleri kumaş ve LED olarak ayrılır. Uydurma ömür yılı eklenmez. Görsel safe margin bırakılır. Sürekli açık senaryoda ısı yönetimi konuşulur.",
    "ofis-branding": "Ofis branding’de sessiz ve tutarlı dil, kalabalık grafikten daha güçlü ilk izlenim bırakır. Resepsiyon, cam ve koridor aynı sistemin parçalarıdır. Plaza kartı/erişim ve yönetim onayı takvimi belirler. Cam folyo ihtiyacı malzemede cam giydirme ile paylaşılsa da paket burada yönetilir. Mesai içi kesinti riski varsa alternatif pencere sunulur. Yeni URL açılmaz. Kanıt için gerçek ofis fotoğrafları proje sayfalarına eklenene kadar noindex kapısı proje tarafında durur. Uydurma ofis sayısı yazılmaz. Renk örneği onayı toplu baskıdan önce alınır. Koridor işaret sıklığı abartılmaz. Ek oda talepleri aynı hatta bağlanır.",
    "totem": "Totem seçiminde yaklaşım hızı, görüş açısı ve zemin koşulları birlikte değerlendirilir. Yüksek yapmak her zaman daha iyi okutmaz. Temel ve izin konuları keşif sonrası netleşir; peşin statik iddia yayınlanmaz. Işıklı totem gece lojistik girişlerinde anlam kazanır. Indoor display ihtiyaçları Display & POS’a aittir. OSB sahalarında montaj penceresi güvenlik kurallarına bağlanır. Tekirdağ niyeti S×C’dedir. Kanıt görselleri onayla yayınlanır.",
}

INDUSTRY_BRIDGE = {
    "fabrika-osb": "Fabrika dikeyinde paket düşüncesi tek ürün satışından daha doğrudur. Totem, tabela, İSG ve filo aynı dilde okunmalıdır. OSB kuralları montajı şekillendirir. Bu sayfa dikey giriştir; sipariş hizmet URL’lerindedir. Uydurma tesis metriği yok. Keşif notları teklifi gerçekçi kılar. Bakım ve yenileme periyotları baştan konuşulur. Bilgi ve proje linkleri kanıt ve eğitim taşır.",
    "restoran-cafe": "F&B dikeyinde gece okunurluk ve vitrin yenilenebilirliği sık birlikte gelir. Menü kalabalığı cepheyi boğmamalıdır. İşletme saatleri montaj penceresini belirler. Dikey sayfa money H1 taşımaz. Gerçek cafe görselleri onayla eklenir. Işıklı ve cam hizmetlerine iç linkler bilinçlidir.",
    "saglik": "Sağlık dikeyinde sakin hiyerarşi güveni korur. Tıbbi iddia üretilmez. Giriş ve bekleme alanları ayrı katmanlardır. Hijyen temizlik rejimini etkiler. Dikey giriş hizmet owner’larına bağlanır. Uydurma klinik sayısı yazılmaz.",
    "plaza-ofis": "Plaza dikeyinde yönetim onayı ve kat erişimi takvimin parçasıdır. Resepsiyon ilk izlenimdir. Ofis branding ve kutu harf sık pakettir. Dikey sayfa sipariş yerine geçmez. Kanıt proje sayfalarındadır.",
    "insaat-santiye": "Şantiye dikeyinde geçici çözüm ile kalıcı kimlik ayrılır. Rüzgâr ve toz panoları yıpratır. İSG eksikleri ayrıca kapatılır. Söküm planı iş bitiminde netleşir. Uydurma şantiye metriği yoktur.",
    "perakende": "Perakende dikeyinde cadde okunurluğu satışa açılır. Açılış paketleri ışıklı ve vitrini birleştirir. Kampanya döngüsü malzeme sınıfını belirler. Zincir şablonları hız kazandırabilir.",
}

ARTICLE_BRIDGE = {
    "tabela-cesitleri": "Bu rehber çeşitleri ayırır; sipariş vermez. Okuma koşulu seçimi belirler. Işıklı tabela ve lightbox bilinçli ayrılır. Son adım ilgili hizmet URL’sidir. Uydurma ‘en iyi tabela’ sıralaması yok.",
    "isikli-mi-isiksiz-mi": "Karar matrisi eğitimdir. Gece ihtiyacı yoksa LED şart değildir. Lightbox ayrı üründür. Sipariş doğru hizmet sayfasından yürür. Abartılı ömür vaadi yok.",
    "kutu-harf-malzemeler": "Malzeme karşılaştırması bilgilendirmedir. Cephe fotoğrafı olmadan kesin öneri eksik kalır. Sipariş kutu harf hizmetindedir. Channel letters ayrı URL değildir.",
    "one-way-vision-nedir": "OWV tanımı ve sınırları burada; uygulama cam giydirmededir. Delik oranı ışığı etkiler. Araç kuralları ayrıdır. Mucize görüş vaadi yok.",
    "arac-giydirme-rehberi": "Süreç ve ömür faktörleri eğitimdir. Full/parça kararı brief’e bağlıdır. Ticari adım hizmet URL’sidir. Genel boya garantisi yoktur.",
    "tabela-fiyati": "Faktör listesi teklif değildir. Keşifsiz rakam bağlayıcı sayılmaz. Geo fiyat S×C bağlamındadır. En ucuz = en doğru değildir.",
    "totem-secim-rehberi": "Konum ve okuma mesafesi seçimi belirler. Indoor display burada değildir. Sipariş totem hizmetindedir. Temel/izin keşifte netleşir.",
}
